#=========================================================================================
#-- Tracking configuration
#=========================================================================================
tracking:
  #---- CONTEXT --------------------------------------------------------------------------
  context:
    type        : GPU
    device_id   : 
  #---------------------------------------------------------------------------------------


  #---- COLLIDER -------------------------------------------------------------------------
  collider:
    path          : colliders/collider_BUNCH_0000.json
    name          : BUNCH_0000
    sequence      : lhcb1
    method        : 6D
  #-----------------------
    # Shortcuts stored below
    cycle_at      : 'IP3'    
    monitor_at    : ['TCP_V', 'TCP_H', 'TCP_S'] 
  #---------------------------------------------------------------------------------------

  #---- PARTICLES ------------------------------------------------------------------------
  particles:
    path              : particles/XY_ZETA_1.parquet
    name              : XY_ZETA_1
  #---------------------------------------------------------------------------------------


  #---- TURN-BY-TURN TRACKING, PARTITIONNED BY CHUNK -------------------------------------
  # Estimate turn-by-turn file size -> 1.2 GB per 1000 turns per 20k particles
  num_turns         : 1e5 
  size_chunks       : 1e3
  #-- Optional
  num_chunks        :
  #---------------------------------------------------------------------------------------



#=========================================================================================
#-- Analysis configuration
#=========================================================================================
analysis:
  path    : tracking/

  #---- TURN-BY-TURN----------------------------------------------------------------------
  turn_by_turn:
    active     : False
  #---------------------------------------------------------------------------------------

  # Chunking for both checkpoints and excursion:
  num_turns : 1e4
  #---- CHECKPOINTS ----------------------------------------------------------------------
  checkpoints :
    active     : True
  #---------------------------------------------------------------------------------------

  #---- EXCURSION ------------------------------------------------------------------------
  excursion:
    active     : True
  #---------------------------------------------------------------------------------------

  #---- NAFF -----------------------------------------------------------------------------
  naff:
    active        : True
    num_turns     : 1e5
    num_harmonics : 50
    window_order  : 4
    window_type   : 'hann'
    #-- Optional
    multiprocesses: 10
  #---------------------------------------------------------------------------------------


#=========================================================================================
#-- Shortcuts for element names
#=========================================================================================
elements:
  lhcb1:
    IP3     : ip3
    TCP_V   : tcp.d6l7.b1
    TCP_H   : tcp.c6l7.b1
    TCP_S   : tcp.b6l7.b1
    IP1_in  : mq.30l1.b1
    IP1_out : mq.30r1.b1

  lhcb2:
    IP3     : ip3
    TCP_V   : tcp.d6r7.b2
    TCP_H   : tcp.c6r7.b2
    TCP_S   : tcp.b6r7.b2
