config_mad:
    # Links to be made for tools and scripts
    # links:
    #   acc-models-lhc: /afs/cern.ch/eng/lhc/optics/runIII 

    # Optics file
    optics_file: acc-models-lhc/optics/opticsfile.32

    # Beam parameters
    beam_config:
      lhcb1:
        beam_energy_tot: 6800           # [GeV]
      lhcb2:
        beam_energy_tot: 6800           # [GeV]

    # Enable machine imperfections
    enable_imperfections: false

    # Enable knob synthesis (for coupling correction, if no imperfections)
    enable_knob_synthesis: false

    # Rename the coupling knobs to avoid conflict between b1 and b2
    # (for hllhc using old fortran code to generate the knobs)
    rename_coupling_knobs: true

    # Optics version, for choice of correction algorithms
    # (ver_lhc_run or ver_hllhc_optics)
    ver_hllhc_optics: null
    ver_lhc_run: 3.0

    # Parameters for machine imperfections
    pars_for_imperfections:
      par_myseed: 1
      par_correct_for_D2: 0
      par_correct_for_MCBX: 0
      par_on_errors_LHC: 1
      par_off_errors_Q4_inIP15: 0
      par_off_errors_Q5_inIP15: 0
      par_on_errors_MBH: 1
      par_on_errors_Q4: 1
      par_on_errors_D2: 1
      par_on_errors_D1: 1
      par_on_errors_IT: 1
      par_on_errors_MCBRD: 0
      par_on_errors_MCBXF: 0
      par_on_errors_NLC: 0
      par_write_errortable: 1

config_knobs_and_tuning:

    knob_settings:

      # Orbit knobs
      on_x1: 250            # [urad]
      on_sep1: 0            # [mm]
      on_x2: 0              # [urad]
      on_sep2: 1.0          # [mm]
      on_x5: 250            # [urad]
      on_sep5: 0            # [mm]
      on_x8: 0              # [urad]
      on_sep8: -1.0         # [mm]
      on_a1: 0              # [urad]
      on_o1: 0              # [mm]
      on_a2: 0              # [urad]
      on_o2: 0              # [mm]
      on_a5: 0              # [urad]
      on_o5: 0              # [mm]
      on_a8: 0              # [urad]
      on_o8: 0              # [mm]
      on_disp: 1            # Value to choose could be optics-dependent


      # Magnets of the experiments
      on_alice_normalized: 1
      on_lhcb_normalized: 1
      on_sol_atlas: 0
      on_sol_cms: 0
      on_sol_alice: 0

      # RF voltage and phases
      vrf400:       12.0            # [MV]
      lagrf400.b1:   0.5            # [rad]
      lagrf400.b2:   0.             # [rad]

      # Octupoles
      i_oct_b1:     350            # [A]
      i_oct_b2:     350            # [A]

    closed_orbit_correction:
      lhcb1: corr_co_lhcb1.json
      lhcb2: corr_co_lhcb2.json

    # Tunes and chromaticities
    qx:
      lhcb1: 62.31
      lhcb2: 62.31
    qy:
      lhcb1: 60.32
      lhcb2: 60.32
    dqx:
      lhcb1: 15
      lhcb2: 15
    dqy:
      lhcb1: 15
      lhcb2: 15

    knob_names:
      lhcb1:
        q_knob_1: dqx.b1_sq
        q_knob_2: dqy.b1_sq
        dq_knob_1: dqpx.b1_sq
        dq_knob_2: dqpy.b1_sq
        c_minus_knob_1: c_minus_re_b1
        c_minus_knob_2: c_minus_im_b1
      lhcb2:
        q_knob_1: dqx.b2_sq
        q_knob_2: dqy.b2_sq
        dq_knob_1: dqpx.b2_sq
        dq_knob_2: dqpy.b2_sq
        c_minus_knob_1: c_minus_re_b2
        c_minus_knob_2: c_minus_im_b2

config_beambeam:
    bunch_spacing_buckets: 10
    num_slices_head_on: 11
    num_long_range_encounters_per_side:
      ip1: 25
      ip2: 20
      ip5: 25
      ip8: 20
    sigma_z: 0.076
    num_particles_per_bunch: 1.4e11
    nemitt_x: 2.0e-6
    nemitt_y: 2.0e-6
    # mask_with_filling_pattern:
    #   pattern_fname: ../filling_scheme/25ns_2228b_2216_1686_2112_hybrid_8b4e_2x56b_25ns_3x48b_12inj.json
    #   i_bunch_b1: 1963 # If not specified, the bunch with the worst schedule is chosen
    #   i_bunch_b2: 1963 # Same. A value for i_bunch_b1 and i_bunch_b2 must be specified if pattern_fname is specified


config_lumi_leveling: 
  ip1:
    luminosity: 2.0e+34
    num_colliding_bunches: null # This will be set automatically according to the filling scheme
    vary:
      - num_particles_per_bunch
    constraints:
      max_intensity: 1.8e11
      max_PU: 70
  ip5:
    luminosity: 2.0e+34
    num_colliding_bunches: null # This will be set automatically according to the filling scheme
    vary:
      - num_particles_per_bunch
    constraints:
      max_intensity: 1.8e11
      max_PU: 70

  ip2:
    separation_in_sigmas: 5
    plane: 'x'
    impose_separation_orthogonal_to_crossing: false
    knobs:
      - on_sep2
    bump_range:
      lhcb1:
        - e.ds.l2.b1
        - s.ds.r2.b1
      lhcb2:
        - s.ds.r2.b2
        - e.ds.l2.b2
    preserve_angles_at_ip: true
    preserve_bump_closure: true
    corrector_knob_names:
      # to preserve angles at ip
      - corr_co_acbyvs4.l2b1
      - corr_co_acbyhs4.l2b1
      - corr_co_acbyvs4.r2b2
      - corr_co_acbyhs4.r2b2
      # to close the bumps
      - corr_co_acbyvs4.l2b2
      - corr_co_acbyhs4.l2b2
      - corr_co_acbyvs4.r2b1
      - corr_co_acbyhs4.r2b1
      - corr_co_acbyhs5.l2b2
      - corr_co_acbyvs5.l2b2
      - corr_co_acbchs5.r2b1
      - corr_co_acbcvs5.r2b1

  ip8:
    luminosity: 2.0e+33
    num_colliding_bunches: null
    impose_separation_orthogonal_to_crossing: false
    knobs:
      - on_sep8
    bump_range:
      lhcb1:
        - e.ds.l8.b1
        - s.ds.r8.b1
      lhcb2:
        - s.ds.r8.b2
        - e.ds.l8.b2
    preserve_angles_at_ip: true
    preserve_bump_closure: true
    corrector_knob_names:
      # to preserve angles at ip
      - corr_co_acbyvs4.l8b1
      - corr_co_acbyhs4.l8b1
      - corr_co_acbyvs4.r8b2
      - corr_co_acbyhs4.r8b2
      # to close the bumps
      - corr_co_acbyvs4.l8b2
      - corr_co_acbyhs4.l8b2
      - corr_co_acbyvs4.r8b1
      - corr_co_acbyhs4.r8b1
      - corr_co_acbcvs5.l8b2
      - corr_co_acbchs5.l8b2
      - corr_co_acbyvs5.r8b1
      - corr_co_acbyhs5.r8b1