# Configuration of the collimators
collimators:
  # Beam 1
  tcp.d6l7.b1:
    tilt: 90.0
    gap : 1.860e-3
  tcp.c6l7.b1:
    tilt: 0.0
    gap : 2.602e-3
  tcp.b6l7.b1:
    tilt: 127.5
    gap : 2.189e-3

  # Beam 2
  tcp.d6r7.b2:
    tilt: 90.0
    gap : 1.834e-3
  tcp.c6r7.b2:
    tilt: 0.0
    gap : 2.593e-3
  tcp.b6r7.b2:
    tilt: 127.5
    gap : 2.152e-3