#======================================================
#-- Tracking configuration
#======================================================

tracking:

  user_context  : GPU
  collider_path : ../001_configure_collider/zfruits/collider_001.json
  
  sequence          : lhcb1
  monitor_at_element: 'TCP_V'    # shortcuts stored below

  n_parts : 20e2
  

  
  # #=========================================
  # parquet_path : zfruits/split_tracking_2s
  # n_turns : 22490

  # # Estimate file size -> 1 GB per 1000 turns per 20k particles
  # partition_turns    : false
  # partition_n_chunks : 50
  
  # # Data processing
  # process_data       : true
  # process_n_turns    : null
  # process_n_chunks   : 50
  # #=========================================


  # #=========================================
  # parquet_path : zfruits/split_tracking_v2
  # n_turns : 2000

  # # Estimate file size -> 1 GB per 1000 turns per 20k particles
  # partition_turns    : true
  # partition_n_chunks : 10
  
  # # Data processing
  # process_data       : false
  # process_n_turns    : null
  # process_n_chunks   : null
  # #=========================================

  # #=========================================
  # parquet_path : zfruits/processed_tracking_2s
  # n_turns : 22490

  # # Estimate file size -> 1 GB per 1000 turns per 20k particles
  # partition_turns    : false
  # partition_n_chunks : null
  
  # # Data processing
  # process_data       : true
  # process_turn_chunk : null
  # process_n_chunks   : 50
  # #=========================================
  

  #=========================================
  parquet_path : zfruits/processed_test_10m
  n_turns : 6747270

  # Estimate file size -> 1 GB per 1000 turns per 20k particles
  partition_turns    : false
  partition_n_chunks : null
  
  # Data processing (sampling 1/s)
  process_data       : true
  process_turn_chunk : 11245
  process_n_chunks   : null
  #=========================================





#======================================================
#-- Shortcuts for element names
#======================================================
elements:
  sequence: lhcb1
    TCP_V: tcp.d6l7.b1
    TCP_H: tcp.c6l7.b1
    TCP_S: tcp.b6l7.b1
  
  sequence: lhcb2
    TCP_V: tcp.d6r7.b2
    TCP_H: tcp.c6r7.b2
    TCP_S: tcp.b6r7.b2