#======================================================
#-- Tracking configuration
#======================================================
# Estimate file size -> 1 GB per 1000 turns per 20k particles
tracking:

  user_context  : CPU
  device_id     : 

  # collider_path : ../001_configure_collider/zfruits/collider_BUNCH_0224.json
  # collider_path : ../001_configure_collider/zfruits/collider_PROBLEM.json
  collider_path : ../001_configure_collider/zfruits/collider_001.json
  sequence     : lhcb1
  monitor_at   : 'TCP_H'    # shortcuts stored below
  bunch_number : 224

  
  

  #=========================================
  n_parts     : 2000
  n_turns     : 6000

  n_chunks    : 
  chunk_size  : 1000

  partition_path     : zfruits/BBB_Signature/FULL
  process_data_path  : zfruits/BBB_Signature/DATA
  checkpoint_path    : zfruits/BBB_Signature/CHECKPOINTS
  #=========================================





#======================================================
#-- Shortcuts for element names
#======================================================
elements:
  lhcb1:
    TCP_V: tcp.d6l7.b1
    TCP_H: tcp.c6l7.b1
    TCP_S: tcp.b6l7.b1
  
  lhcb2:
    TCP_V: tcp.d6r7.b2
    TCP_H: tcp.c6r7.b2
    TCP_S: tcp.b6r7.b2