#======================================================
#-- Tracking configuration
#======================================================
# Estimate file size -> 1 GB per 1000 turns per 20k particles
tracking:

  user_context  : GPU
  device_id     : 2

  collider_path : ../001_configure_collider/zfruits/collider_001.json
  sequence     : lhcb1
  monitor_at   : 'TCP_H'    # shortcuts stored below
  bunch_number : 224

  
  

  #=========================================
  n_parts     : 20e3
  n_turns     : 22490

  n_chunks    : 
  chunk_size  : 1000

  partition_path     : zfruits/BBB_Signature_V2/FULL/BUNCH_0000
  process_data_path  : zfruits/BBB_Signature_V2/DATA
  checkpoint_path    : zfruits/BBB_Signature_V2/CHECKPOINTS
  #=========================================





#======================================================
#-- Shortcuts for element names
#======================================================
elements:
  lhcb1:
    TCP_V: tcp.d6l7.b1
    TCP_H: tcp.c6l7.b1
    TCP_S: tcp.b6l7.b1
  
  lhcb2:
    TCP_V: tcp.d6r7.b2
    TCP_H: tcp.c6r7.b2
    TCP_S: tcp.b6r7.b2