#======================================================
#-- Tracking configuration
#======================================================

tracking:

  user_context  : GPU
  collider_path : ../001_configure_collider/zfruits/collider_001.json
  tracking_path : zfruits/tracking

  sequence: lhcb1
  n_parts : 20e3
  n_turns : 1e3


monitor:

  start_at_turn    : 0
  stop_at_turn     : n_turns
  n_repetitions    : 1
  repetition_period: 1





