#=========================================================================================
#-- PARTICLE DISTRIBUTION
#=========================================================================================

#---- COLLIDER ---------------------------------------------------------------------------
collider:
  path    : /Users/pbelanger/ABPLocal/BBStudies/examples/run_xmask_jobs/colliders/collider_BUNCH_0000.json
  sequence: lhcb1
  cycle_at: IP3
#-----------------------------------------------------------------------------------------


#---- PARTICLES --------------------------------------------------------------------------
particles:
  path: ./particles
  name: HYPERSPHERE

  #-- DISTRIBUTION
  type          : hypersphere
  num_particles : 20e3
#-----------------------------------------------------------------------------------------

#---- DISTRIBUTIONS ----------------------------------------------------------------------
hypersphere:
  seed      : 0
  rx_sig    : 8
  ry_sig    : 8
  rzeta_sig : 2.5
#--------------------------------------------
grid:
  offset_x : 1e-6
  offset_y : 1e-6
  max_x    : 10
  max_y    : 10
  zeta     : 1
#-----------------------------------------------------------------------------------------



#=========================================================================================
#-- Shortcuts for element names
#=========================================================================================
elements:
  lhcb1:
    IP3     : ip3
    TCP_V   : tcp.d6l7.b1
    TCP_H   : tcp.c6l7.b1
    TCP_S   : tcp.b6l7.b1
    IP1_in  : mq.30l1.b1
    IP1_out : mq.30r1.b1

  lhcb2:
    IP3     : ip3
    TCP_V   : tcp.d6r7.b2
    TCP_H   : tcp.c6r7.b2
    TCP_S   : tcp.b6r7.b2
